(prelude-require-package 'delight)
(delight '((abbrev-mode nil abbrev)
           (eldoc-mode nil "eldoc")
           (guru-mode)
           (company-mode nil company)
           (ivy-mode nil ivy)
           (editorconfig-mode nil editorconfig)
           (whitespace-mode nil t)
           (super-save-mode nil super-save)
           (prelude-mode)
           (which-key-mode nil which-key)
           (org-indent-mode nil org-indent)
           (beacon-mode nil beacon)))
